### ISSUE TITLE
mvn client:build on macOs 10.15 error

### ISSUE THREAD

**Issue by thinkiny** [gluonhq/client-samples#83]
Wed May 27 14:29:05 CST 2020][FINE] PB Command for compile-additional-sources: gcc -c -DSUBSTRATE -I/Users/aaron/projects/client-samples/Maven/HelloFX/target/client/x86_64-darwin/gvm/hellofx AppDelegate.m launcher.c
[Wed May 27 14:29:05 CST 2020][FINE] Start process compile-additional-sources...
[Wed May 27 14:29:05 CST 2020][FINE] [SUB] AppDelegate.m:28:9: fatal error: 'Cocoa/Cocoa.h' file not found
[Wed May 27 14:29:05 CST 2020][FINE] [SUB] #import <Cocoa/Cocoa.h>
[Wed May 27 14:29:05 CST 2020][FINE] [SUB]         ^~~~~~~~~~~~~~~
[Wed May 27 14:29:05 CST 2020][FINE] [SUB] AppDelegate.m:28:9: note: did not find header 'Cocoa.h' in framework 'Cocoa' (loaded from '/System/Library/Frameworks')
[Wed May 27 14:29:05 CST 2020][FINE] [SUB] 1 error generated.
[Wed May 27 14:29:05 CST 2020][FINE] Result for compile-additional-sources: 1
[Wed May 27 14:29:05 CST 2020][SEVERE] Process compile-additional-sources failed with result: 1
Check the log files under /Users/aaron/projects/client-samples/Maven/HelloFX/target/client/x86_64-darwin/gvm/log

Xcode 11.5

**Comment by thinkiny** [comment]
i found a solution, :)
